get:
  parameters:
    - name: id
      in: path
      required: true
      description: The id of the asset to retrieve
      schema:
        type: string
      example: "svc-demo-svc"
    - in: query
      name: params
      schema:
        type: object
      style: form
      explode: true
  summary: An array of envionments data for an asset
  operationId: listEnvironmentsByAssetId
  tags:
    - assetsByEnvironment
  responses:
    "200":
      description: An array of environments data
      headers:
        $ref: "./common-headers.yaml#/response"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/AssetsEnvironment"
    default:
      description: unexpected error
      content:
        application/json:
          schema:
            $ref: "./Error.yaml"

components:
  schemas:
    AssetsEnvironment:
      type: array
      items:
        $ref: "#/components/schemas/AssetEnvironment"
    AssetEnvironment:
      type: object
      anyOf:
        - $ref: "./openapi-schemas/SvcByEnvironment.json"
        - $ref: "./openapi-schemas/AppByEnvironment.json"
        - $ref: "./openapi-schemas/BffByEnvironment.json"
