get:
  summary: Environment data for a specific asset on a specific environment
  operationId: getAssetEnvironmentById
  tags:
    - assetsByEnvironment
  parameters:
    - name: id
      in: path
      required: true
      description: The id of the asset to retrieve
      schema:
        type: string
      example: "svc-demo-svc"
    - name: environmentId
      in: path
      required: true
      description: The id of the environment to retrieve
      schema:
        type: string
      example: "us-prod"
  responses:
    "200":
      description: Expected response to a valid request
      headers:
        $ref: "./common-headers.yaml#/response"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/AssetEnvironment"


components:
  schemas:
    AssetsEnvironment:
      type: array
      items:
        $ref: "#/components/schemas/AssetEnvironment"
    AssetEnvironment:
      type: object
      anyOf:
        - $ref: "./openapi-schemas/SvcByEnvironment.json"
        - $ref: "./openapi-schemas/AppByEnvironment.json"
        - $ref: "./openapi-schemas/BffByEnvironment.json"