get:
  summary: Get all products
  operationId: listProducts
  tags:
    - products
  responses:
    "200":
      description: An array of products
      headers:
        $ref: "./common-headers.yaml#/response"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Products"
    default:
      description: unexpected error
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
post:
  summary: Create new product
  tags:
    - products
  operationId: createProduct
  consumes:
    - application/json
  produces:
    - application/json
  parameters:
    - in: "body"
      name: "body"
      description: Create a new product entity within app-registry.
      required: true
      schema:
        $ref: "./json-schemas/Product.json"
  responses:
    "200":
      description: Product record inserted
    default:
      description: Product insert failed
components:
  schemas:
    Products:
      type: array
      items:
        $ref: "#/components/schemas/Product"
    Product:
      type: object
      $ref: "./openapi-schemas/Product.json"
    Error:
      type: object
      $ref: "Error.yaml"
