# Generated by Django 3.2.2 on 2021-05-11 00:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.UUIDField(db_column='id', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=50, unique=True)),
                ('properties', models.JSONField(blank=True, db_column='properties', null=True)),
            ],
            options={
                'verbose_name': 'Environments',
                'db_table': 'Environment',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.UUIDField(db_column='id', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=255, unique=True)),
                ('properties', models.JSONField(blank=True, db_column='properties', null=True)),
                ('deleted', models.BooleanField(db_column='deleted', default='f')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', null=True)),
                ('created_by', models.CharField(blank=True, db_column='created_by', max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at', null=True)),
                ('updated_by', models.CharField(blank=True, db_column='updated_by', max_length=100, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', null=True)),
            ],
            options={
                'verbose_name': 'Teams',
                'db_table': 'Team',
                'ordering': ['-updated_at', '-created_at'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(db_column='id', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=255, unique=True)),
                ('properties', models.JSONField(blank=True, db_column='properties', null=True)),
                ('deleted', models.BooleanField(db_column='deleted', default='f')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', null=True)),
                ('created_by', models.CharField(blank=True, db_column='created_by', max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at', null=True)),
                ('updated_by', models.CharField(blank=True, db_column='updated_by', max_length=100, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', null=True)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='athena_app_cmdb.environment')),
            ],
            options={
                'verbose_name': 'Locations',
                'db_table': 'Location',
                'ordering': ['-updated_at', '-created_at'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.UUIDField(db_column='id', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=255, unique=True)),
                ('properties', models.JSONField(blank=True, db_column='properties', null=True)),
                ('deleted', models.BooleanField(db_column='deleted', default='f')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', null=True)),
                ('created_by', models.CharField(blank=True, db_column='created_by', max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at', null=True)),
                ('updated_by', models.CharField(blank=True, db_column='updated_by', max_length=100, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='athena_app_cmdb.location')),
            ],
            options={
                'verbose_name': 'Kubernetes Clusters',
                'db_table': 'Cluster',
                'ordering': ['-updated_at', '-created_at'],
                'managed': True,
            },
        ),
    ]
