# Generated by Django 3.2.3 on 2021-06-07 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('athena_app_cmdb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applanguage',
            name='updated_by',
        ),
    ]
