# Generated by Django 3.2.2 on 2021-05-11 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athena_app_cmdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cluster',
            options={'managed': True, 'ordering': ['-updated_at', '-created_at'], 'verbose_name': 'Kubernetes Cluster'},
        ),
        migrations.AlterModelOptions(
            name='environment',
            options={'managed': True, 'verbose_name': 'Environment'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'managed': True, 'ordering': ['-updated_at', '-created_at'], 'verbose_name': 'Location'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'managed': True, 'ordering': ['-updated_at', '-created_at'], 'verbose_name': 'Team'},
        ),
        migrations.AddField(
            model_name='environment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='created_at', null=True),
        ),
        migrations.AddField(
            model_name='environment',
            name='created_by',
            field=models.CharField(blank=True, db_column='created_by', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='environment',
            name='deleted',
            field=models.BooleanField(db_column='deleted', default='f'),
        ),
        migrations.AddField(
            model_name='environment',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_column='deleted_at', null=True),
        ),
        migrations.AddField(
            model_name='environment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='updated_at', null=True),
        ),
        migrations.AddField(
            model_name='environment',
            name='updated_by',
            field=models.CharField(blank=True, db_column='updated_by', max_length=100, null=True),
        ),
    ]
