# Generated by Django 3.2.4 on 2021-06-08 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athena_app_cmdb', '0002_remove_applanguage_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetenvironment',
            name='refid',
            field=models.CharField(db_column='environment_id', max_length=100),
        ),
    ]
