# Generated by Django 3.2.4 on 2021-06-08 23:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('athena_app_cmdb', '0003_alter_assetenvironment_refid'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetenvironment',
            name='product_environment',
            field=models.ForeignKey(default='d4165813-026d-467f-9e11-b910eb0924b8', on_delete=django.db.models.deletion.PROTECT,
                                    to='athena_app_cmdb.productenvironment'),
            preserve_default=False,
        ),
    ]
