# Generated by Django 3.2.4 on 2021-06-09 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('athena_app_cmdb', '0004_assetenvironment_product_environment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AssetBackup',
        ),
    ]
