# Generated by Django 3.2.4 on 2021-06-14 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('athena_app_cmdb', '0005_delete_assetbackup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetenvironment',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='athena_app_cmdb.asset'),
        ),
    ]
