# Generated by Django 3.2.7 on 2021-09-17 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athena_app_cmdb', '0006_alter_assetenvironment_asset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(db_column='name', max_length=100),
        ),
    ]
