# Generated by Django 3.2.9 on 2021-12-15 08:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('athena_app_cmdb', '0007_alter_team_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingRequest',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', null=True)),
                ('original_id', models.CharField(blank=True, db_column='original_id', max_length=255, null=True)),
                ('id', models.UUIDField(db_column='id', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('refid', models.CharField(db_column='onboarding_request_id', max_length=100, unique=True)),
                ('properties', models.JSONField(blank=True, db_column='json', null=True)),
                ('deleted', models.BooleanField(db_column='deleted', default='f')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at', null=True)),
                ('created_by', models.CharField(blank=True, db_column='created_by', max_length=100, null=True)),
                ('updated_by', models.CharField(blank=True, db_column='updated_by', max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Onboarding Request',
                'db_table': 'onboarding_request',
                'ordering': ['-updated_at', '-created_at'],
                'managed': True,
            },
        ),
    ]
