# Generated by Django 3.2.9 on 2022-01-05 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athena_app_cmdb', '0008_onboardingrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardingrequest',
            name='approved_by',
            field=models.CharField(blank=True, db_column='approved_by', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='onboardingrequest',
            name='completed_by',
            field=models.CharField(blank=True, db_column='completed_by', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='onboardingrequest',
            name='datetime_approved',
            field=models.DateTimeField(auto_now=True, db_column='datetime_approved', null=True),
        ),
        migrations.AddField(
            model_name='onboardingrequest',
            name='datetime_completed',
            field=models.DateTimeField(auto_now=True, db_column='datetime_completed', null=True),
        ),
        migrations.AddField(
            model_name='onboardingrequest',
            name='datetime_rejected',
            field=models.DateTimeField(auto_now=True, db_column='datetime_rejected', null=True),
        ),
        migrations.AddField(
            model_name='onboardingrequest',
            name='deleted_by',
            field=models.CharField(blank=True, db_column='deleted_by', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='onboardingrequest',
            name='rejected_by',
            field=models.CharField(blank=True, db_column='rejected_by', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='onboardingrequest',
            name='request_owner',
            field=models.CharField(db_column='request_owner', default='null', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='onboardingrequest',
            name='request_status',
            field=models.CharField(db_column='request_status', default='New', max_length=100),
        ),
    ]
