
# Deployment definition
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "helm.labels" . }}
spec:
  progressDeadlineSeconds: {{ .Values.progressDeadlineSeconds }}
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      app.cdk.com/id: "athena-app-cmdb"
  template:
    metadata:
      annotations:
        createdAt: {{ now | date "2006-01-02T15:04:05Z07:00" | quote }} # Force canary analysis upon every deployment
    {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "helm.labels" . | indent 4 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Values.name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ .Values.image }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.containerPort }}
              protocol: TCP
          livenessProbe:
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
            httpGet:
              path: {{ .Values.livenessProbe.httpGet.path }}
              port: {{ .Values.livenessProbe.httpGet.port }}
              scheme: {{ .Values.livenessProbe.httpGet.scheme }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            successThreshold: {{ .Values.livenessProbe.successThreshold }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
          readinessProbe:
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
            httpGet:
              path: {{ .Values.readinessProbe.httpGet.path }}
              port: {{ .Values.readinessProbe.httpGet.port }}
              scheme: {{ .Values.readinessProbe.httpGet.scheme }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            successThreshold: {{ .Values.readinessProbe.successThreshold }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
          {{- if .Values.env.bamboo_username }}
          - name: bamboo_username
            value: {{ .Values.env.bamboo_username }}
          {{- end }}
          {{- if .Values.env.bamboo_password }}
          - name: bamboo_password
            value: {{ .Values.env.bamboo_password }}
          {{- end }}
          {{- if .Values.env.bamboo_resources_plan }}
          - name: bamboo_resources_plan
            value: {{ .Values.env.bamboo_resources_plan }}
          {{- end }}
          {{- if .Values.env.bamboo_resources_secret_plan }}
          - name: bamboo_resources_secret_plan
            value: {{ .Values.env.bamboo_resources_secret_plan }}
          {{- end }}
          {{- if  .Values.env.django_settings_module }}
          - name: DJANGO_SETTINGS_MODULE
            value: {{ .Values.env.django_settings_module }}
          {{- end }}
          {{- if .Values.secret_key }}
          - name: SECRET_KEY
            value: {{ .Values.secret_key }}
          {{- end }}
          {{- if .Values.environmentVariables }}
            {{- toYaml .Values.environmentVariables | nindent 10 }}
          {{- end }}
          {{- if .Values.externalSecretVars }}
            {{- toYaml .Values.externalSecretVars | nindent 10 }}
          {{- end }}
          - name: environment
            value: {{ .Values.environment }}
          {{- if hasKey .Values "hasRdsDatabase" }}
          - name: DB_CONFIG
            valueFrom:
              secretKeyRef:
                name: {{ .Values.name }}-db-secret
                key: db-config
          {{- end }}
          {{- if hasKey .Values "hasElasticCache" }}
          - name: REDIS_CONFIG
            valueFrom:
              secretKeyRef:
                name: {{ .Values.name }}-redis-secret
                key: redis-config
          {{- end }}
          {{- if hasKey .Values "managedSecrets" }} 
          {{- range $k, $v := .Values.managedSecrets }}
          - name: {{  $v.name }}
            valueFrom:
              secretKeyRef:
                name: {{ $v.secretKeyRefName }}
                key: value
                optional: true
          {{- end }}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
