apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: athena-cmdb-rds
spec:
  hosts:
  - {{ .Values.rds_host }}
  ports:
  - number: {{ .Values.rds_port }}
    name: tcp
    protocol: TCP
  resolution: DNS
  location: MESH_EXTERNAL

