paths:
  /locations:
    model: locations
    post:
      required_inputs:
        name:
          type: string
        environment:
          type: uuid
      optional_inputs:
        properties.old_version_id:
          type: unique
        properties.domain:
          type: string
        properties.region:
          type: string
          default: us
          choices:
            - us
        properties.status:
          type: string
          default: live


  /clusters:
    model: clusters
    post:
      required_inputs:
        name:
          type: string
      optional_inputs:
        properties.uri:
          type: string
      location_name:
        type: lookup_field
        model: locations
        lookup_key: name
        src_key: id
        dst_key: location
        example: aws us-prod
  /teams:
    model: teams
    post:
      required_inputs:
        name:
          type: string
        properties.email:
          type: array
        properties.ad-group:
          type: array
        properties.notification:
          type: array
      optional_inputs:
        description:
          type: string