# Generated by Django 3.2 on 2021-05-09 13:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=75)),
                ('properties', models.JSONField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asset_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('properties', models.JSONField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('properties', models.JSONField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='EgressRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('properties', models.JSONField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('properties', models.JSONField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('properties', models.JSONField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('properties', models.JSONField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('properties', models.JSONField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='SecurityProvider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('properties', models.JSONField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('properties', models.JSONField(default=None)),
            ],
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_team_name'),
        ),
        migrations.AddConstraint(
            model_name='securityprovider',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_security_name'),
        ),
        migrations.AddField(
            model_name='resource',
            name='environment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.environment'),
        ),
        migrations.AddField(
            model_name='product',
            name='environment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.environment'),
        ),
        migrations.AddField(
            model_name='location',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.account'),
        ),
        migrations.AddField(
            model_name='environment',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.location'),
        ),
        migrations.AddField(
            model_name='egressrule',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.asset'),
        ),
        migrations.AddField(
            model_name='cluster',
            name='environment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.environment'),
        ),
        migrations.AddField(
            model_name='asset',
            name='clusters',
            field=models.ManyToManyField(to='api.Cluster'),
        ),
        migrations.AddField(
            model_name='asset',
            name='environment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.environment'),
        ),
        migrations.AddField(
            model_name='asset',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product'),
        ),
        migrations.AddField(
            model_name='asset',
            name='securities',
            field=models.ManyToManyField(to='api.SecurityProvider'),
        ),
        migrations.AddField(
            model_name='asset',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.team'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_account_name'),
        ),
        migrations.AddConstraint(
            model_name='resource',
            constraint=models.UniqueConstraint(fields=('name', 'environment'), name='unique_resource_name'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('name', 'environment'), name='unique_product_name'),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_location_name'),
        ),
        migrations.AddConstraint(
            model_name='environment',
            constraint=models.UniqueConstraint(fields=('name', 'location'), name='unique_environment_name'),
        ),
        migrations.AddConstraint(
            model_name='egressrule',
            constraint=models.UniqueConstraint(fields=('name', 'asset'), name='unique_egress_name'),
        ),
        migrations.AddConstraint(
            model_name='cluster',
            constraint=models.UniqueConstraint(fields=('name', 'environment'), name='unique_cluster_name'),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.UniqueConstraint(fields=('asset_id', 'environment'), name='unique_asset_assetid'),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.UniqueConstraint(fields=('name', 'environment'), name='unique_asset_name'),
        ),
    ]
