apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.extSecretName }}
  namespace: {{ .Values.namespace }}
spec:
  backendType: secretsManager
  roleArn: {{ .Values.roleArn }}
  data:
    - key: {{ .Values.sourceSecretKey }}
      name: {{ .Values.secretName }}