id: app-athena-root-config
name: athena-uip-root-config-app
description: Athena UIP Root Config
type: app
_type: asset
icon: school
color: "#FFC107"
assetMasterId: 325
appLanguage: reactjs
team: team-athena-uip
product: athena-uip
repo: https://stash.cdk.com/projects/ATU/repos/app-athena-root-config/browse
cicd: https://bamboo.cdk.com/browse/AUIP-APPATHENAROOTCONFIG
internal: false
consumes:
  - value: svc-athena-registry
    path: /api/*
    type: service
